BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/tty.usbmodem*
ARDUINO_LIBS = Arduino-PID-Library/PID_v1 OneWire DallasTemperature Arduino-PID-AutoTune-Library/PID_AutoTune_v0

USER_LIB_PATH = ..

include ../Arduino-Makefile/arduino-mk/Arduino.mk
